import type {
  CarrierPerformance,
  CarrierStatus,
  Customer,
  DelayReasonSummary,
  ExceptionRecord,
  Shipment,
  ShipmentStatus,
  WeeklyTrendPoint,
} from "./types";
import { generateTrackingNumber, resolveCarrierKey } from "./carriers";
import { assignPlaybook, getRecommendedAction } from "./playbooks";

type ShipmentBase = Omit<
  Shipment,
  "trackingNumber" | "carrierStatus" | "lastCarrierUpdate" | "estimatedDelivery" | "actualDelivery"
>;

const STATUS_TO_CARRIER: Record<ShipmentStatus, CarrierStatus> = {
  "In Transit": "In Transit",
  Delayed: "Delayed",
  Delivered: "Delivered",
  Exception: "Exception",
};

function enrichCarrierTracking(shipment: ShipmentBase): Shipment {
  const key = resolveCarrierKey(shipment.carrier);
  if (!key) {
    return {
      ...shipment,
      trackingNumber: null,
      carrierStatus: null,
      lastCarrierUpdate: null,
      estimatedDelivery: null,
      actualDelivery: null,
    };
  }

  return {
    ...shipment,
    trackingNumber: generateTrackingNumber(shipment.id, key),
    carrierStatus: STATUS_TO_CARRIER[shipment.status],
    lastCarrierUpdate: "May 28, 2026 · 08:30",
    estimatedDelivery: shipment.status !== "Delivered" ? shipment.eta : null,
    actualDelivery: shipment.status === "Delivered" ? shipment.eta : null,
  };
}

const baseShipmentRows: ShipmentBase[] = [
  {
    id: "FP-2026-084219",
    customer: "Meridian Industrial Supply",
    carrier: "XPO Logistics",
    mode: "LTL",
    origin: "Joliet, IL",
    destination: "Charlotte, NC",
    eta: "May 28, 2026 · 14:00",
    originalEta: "May 27, 2026 · 09:00",
    delayHours: 29,
    delayReason: "Missed linehaul connection at Nashville hub",
    severity: "High",
    status: "Delayed",
    issueStatus: "Investigating",
    exception: "Pro number re-rated; customer notified",
  },
  {
    id: "FP-2026-084156",
    customer: "Coastal Retail Group",
    carrier: "FedEx Freight",
    mode: "LTL",
    origin: "Ontario, CA",
    destination: "Phoenix, AZ",
    eta: "May 29, 2026 · 11:30",
    originalEta: "May 28, 2026 · 16:00",
    delayHours: 19,
    delayReason: "Severe weather — I-10 corridor closure",
    severity: "Medium",
    status: "Delayed",
    issueStatus: "Awaiting Carrier",
    exception: "Carrier ETA revision pending",
  },
  {
    id: "FP-2026-083902",
    customer: "NorthStar Medical Devices",
    carrier: "Old Dominion Freight",
    mode: "LTL",
    origin: "Memphis, TN",
    destination: "Boston, MA",
    eta: "May 27, 2026 · 08:00",
    originalEta: "May 27, 2026 · 08:00",
    delayHours: null,
    delayReason: "—",
    severity: "Low",
    status: "Delivered",
    issueStatus: "Resolved",
    exception: "POD signed — dock 4, Revere MA",
  },
  {
    id: "FP-2026-084301",
    customer: "Summit Automotive Parts",
    carrier: "Schneider National",
    mode: "FTL",
    origin: "Detroit, MI",
    destination: "Dallas, TX",
    eta: "May 30, 2026 · 06:00",
    originalEta: "May 28, 2026 · 22:00",
    delayHours: 32,
    delayReason: "Driver HOS reset — mandatory 10-hr break",
    severity: "Critical",
    status: "Exception",
    issueStatus: "Escalated",
    exception: "SLA breach risk — $12k/hr line stoppage",
  },
  {
    id: "FP-2026-084088",
    customer: "Pacific Home Goods",
    carrier: "Saia LTL Freight",
    mode: "LTL",
    origin: "Portland, OR",
    destination: "Denver, CO",
    eta: "May 28, 2026 · 17:00",
    originalEta: "May 28, 2026 · 12:00",
    delayHours: 5,
    delayReason: "Address verification — suite number mismatch",
    severity: "Medium",
    status: "Exception",
    issueStatus: "Pending Customer",
    exception: "Consignee contact attempted ×2",
  },
  {
    id: "FP-2026-083744",
    customer: "Greenfield Foods Co-op",
    carrier: "Werner Enterprises",
    mode: "Reefer",
    origin: "Salinas, CA",
    destination: "Chicago, IL",
    eta: "May 29, 2026 · 04:00",
    originalEta: "May 29, 2026 · 04:00",
    delayHours: null,
    delayReason: "—",
    severity: "Low",
    status: "In Transit",
    issueStatus: "Open",
    exception: "Temp log within range — last ping 2h ago",
  },
  {
    id: "FP-2026-084412",
    customer: "Atlas Construction Supply",
    carrier: "JB Hunt Intermodal",
    mode: "Intermodal",
    origin: "Long Beach, CA",
    destination: "Atlanta, GA",
    eta: "May 31, 2026 · 10:00",
    originalEta: "May 29, 2026 · 14:00",
    delayHours: 44,
    delayReason: "Port congestion — chassis shortage at LBCT",
    severity: "Critical",
    status: "Delayed",
    issueStatus: "Investigating",
    exception: "Demurrage accruing — $185/day",
  },
  {
    id: "FP-2026-084267",
    customer: "Vertex Electronics",
    carrier: "UPS Freight",
    mode: "LTL",
    origin: "Austin, TX",
    destination: "Nashville, TN",
    eta: "May 28, 2026 · 09:00",
    originalEta: "May 28, 2026 · 09:00",
    delayHours: null,
    delayReason: "—",
    severity: "Low",
    status: "In Transit",
    issueStatus: "Open",
    exception: "On schedule — departed Austin terminal 06:12",
  },
  {
    id: "FP-2026-084501",
    customer: "Harbor Textiles",
    carrier: "XPO Logistics",
    mode: "LTL",
    origin: "Savannah, GA",
    destination: "Columbus, OH",
    eta: "May 30, 2026 · 15:00",
    originalEta: "May 29, 2026 · 10:00",
    delayHours: 29,
    delayReason: "Terminal congestion — outbound dock delay",
    severity: "High",
    status: "Delayed",
    issueStatus: "Investigating",
    exception: "Customer ops notified",
  },
  {
    id: "FP-2026-084533",
    customer: "Lakeside Pharma",
    carrier: "FedEx Freight",
    mode: "LTL",
    origin: "Indianapolis, IN",
    destination: "Raleigh, NC",
    eta: "May 28, 2026 · 20:00",
    originalEta: "May 28, 2026 · 20:00",
    delayHours: null,
    delayReason: "—",
    severity: "Low",
    status: "In Transit",
    issueStatus: "Open",
    exception: "Chain of custody intact",
  },
];

export const shipmentRows: Shipment[] = baseShipmentRows.map(enrichCarrierTracking);

export const initialExceptionRecords: ExceptionRecord[] = [
  enrichWithPlaybook(
    {
      id: "EXC-4401",
      shipmentId: "FP-2026-084301",
      title: "SLA breach risk — production line stoppage",
      customer: "Summit Automotive Parts",
      carrier: "Schneider National",
      route: "Detroit, MI → Dallas, TX",
      severity: "Critical",
      status: "Escalated",
      owner: "Sarah Chen",
      delayReason: "Driver HOS reset — mandatory 10-hr break",
      openedAt: "May 27, 2026 · 08:12",
      updatedAt: "5 min ago",
      source: "Manual",
      internalNotes: [
        {
          id: "note-1",
          author: "Sarah Chen",
          body: "Escalated to carrier VP — awaiting callback within 2h.",
          createdAt: "May 27, 2026 · 09:00",
        },
      ],
    },
    { escalationLevel: 2 },
  ),
  enrichWithPlaybook({
    id: "EXC-4398",
    shipmentId: "FP-2026-084412",
    title: "Port demurrage accruing — chassis shortage",
    customer: "Atlas Construction Supply",
    carrier: "JB Hunt Intermodal",
    route: "Long Beach, CA → Atlanta, GA",
    severity: "Critical",
    status: "Investigating",
    owner: "Marcus Webb",
    delayReason: "Port congestion — chassis shortage at LBCT",
    openedAt: "May 26, 2026 · 19:40",
    updatedAt: "22 min ago",
    source: "Manual",
    internalNotes: [],
  }),
  enrichWithPlaybook({
    id: "EXC-4395",
    shipmentId: "FP-2026-084219",
    title: "Missed Nashville linehaul connection",
    customer: "Meridian Industrial Supply",
    carrier: "XPO Logistics",
    route: "Joliet, IL → Charlotte, NC",
    severity: "High",
    status: "Investigating",
    owner: "Lisa Park",
    delayReason: "Missed linehaul connection at Nashville hub",
    openedAt: "May 27, 2026 · 06:30",
    updatedAt: "1 hr ago",
    source: "Manual",
    internalNotes: [],
  }),
  enrichWithPlaybook({
    id: "EXC-4392",
    shipmentId: "FP-2026-084156",
    title: "Weather delay — I-10 corridor closure",
    customer: "Coastal Retail Group",
    carrier: "FedEx Freight",
    route: "Ontario, CA → Phoenix, AZ",
    severity: "Medium",
    status: "Awaiting Carrier",
    owner: "System",
    delayReason: "Severe weather — I-10 corridor closure",
    openedAt: "May 27, 2026 · 04:15",
    updatedAt: "34 min ago",
    source: "Manual",
    internalNotes: [],
  }),
  enrichWithPlaybook({
    id: "EXC-4388",
    shipmentId: "FP-2026-084088",
    title: "Address verification — suite mismatch",
    customer: "Pacific Home Goods",
    carrier: "Saia LTL Freight",
    route: "Portland, OR → Denver, CO",
    severity: "Medium",
    status: "Pending Customer",
    owner: "Sarah Chen",
    delayReason: "Address verification — suite number mismatch",
    openedAt: "May 27, 2026 · 09:00",
    updatedAt: "18 min ago",
    source: "Manual",
    internalNotes: [],
  }),
  enrichWithPlaybook({
    id: "EXC-4381",
    shipmentId: "FP-2026-084501",
    title: "Terminal outbound dock delay",
    customer: "Harbor Textiles",
    carrier: "XPO Logistics",
    route: "Savannah, GA → Columbus, OH",
    severity: "High",
    status: "Open",
    owner: "Marcus Webb",
    delayReason: "Terminal congestion — outbound dock delay",
    openedAt: "May 27, 2026 · 11:20",
    updatedAt: "2 hr ago",
    source: "Manual",
    internalNotes: [],
  }),
];

function enrichWithPlaybook(
  exc: ExceptionRecord,
  overrides?: { escalationLevel?: 1 | 2 | 3 | 4; nextFollowUpAt?: string },
): ExceptionRecord {
  const playbook = assignPlaybook({
    title: exc.title,
    delayReason: exc.delayReason,
    severity: exc.severity,
    source: exc.source,
  });
  const escalationLevel = overrides?.escalationLevel ?? playbook.escalationLevel;
  return {
    ...exc,
    owner: playbook.owner,
    playbookType: playbook.playbookType,
    escalationLevel,
    recommendedAction: getRecommendedAction(playbook.playbookType, escalationLevel),
    nextFollowUpAt:
      overrides?.nextFollowUpAt ??
      new Date(Date.now() - 30 * 60_000).toISOString(),
  };
}

/** @deprecated Use initialExceptionRecords via ExceptionsProvider */
export const exceptionRecords = initialExceptionRecords;

export const customers: Customer[] = [
  {
    id: "CUS-001",
    name: "Meridian Industrial Supply",
    contactName: "Sarah Chen",
    contactEmail: "sarah.chen@freightpulse.io",
    tier: "Enterprise",
    accountManager: "Sarah Chen",
    activeShipments: 142,
    exceptions: 8,
    slaTarget: 97,
    region: "Southeast",
  },
  {
    id: "CUS-002",
    name: "Summit Automotive Parts",
    contactName: "Marcus Webb",
    contactEmail: "marcus.webb@freightpulse.io",
    tier: "Enterprise",
    accountManager: "Marcus Webb",
    activeShipments: 98,
    exceptions: 12,
    slaTarget: 97,
    region: "Midwest",
  },
  {
    id: "CUS-003",
    name: "Coastal Retail Group",
    contactName: "Lisa Park",
    contactEmail: "lisa.park@freightpulse.io",
    tier: "Growth",
    accountManager: "Lisa Park",
    activeShipments: 76,
    exceptions: 5,
    slaTarget: 93,
    region: "West",
  },
  {
    id: "CUS-004",
    name: "NorthStar Medical Devices",
    contactName: "Sarah Chen",
    contactEmail: "sarah.chen@freightpulse.io",
    tier: "Enterprise",
    accountManager: "Sarah Chen",
    activeShipments: 64,
    exceptions: 2,
    slaTarget: 97,
    region: "Northeast",
  },
  {
    id: "CUS-005",
    name: "Atlas Construction Supply",
    contactName: "Marcus Webb",
    contactEmail: "marcus.webb@freightpulse.io",
    tier: "Growth",
    accountManager: "Marcus Webb",
    activeShipments: 51,
    exceptions: 9,
    slaTarget: 93,
    region: "Southeast",
  },
  {
    id: "CUS-006",
    name: "Pacific Home Goods",
    contactName: "Lisa Park",
    contactEmail: "lisa.park@freightpulse.io",
    tier: "Standard",
    accountManager: "Lisa Park",
    activeShipments: 38,
    exceptions: 4,
    slaTarget: 90,
    region: "West",
  },
  {
    id: "CUS-007",
    name: "Greenfield Foods Co-op",
    contactName: "Sarah Chen",
    contactEmail: "sarah.chen@freightpulse.io",
    tier: "Growth",
    accountManager: "Sarah Chen",
    activeShipments: 44,
    exceptions: 1,
    slaTarget: 93,
    region: "West",
  },
  {
    id: "CUS-008",
    name: "Vertex Electronics",
    contactName: "Lisa Park",
    contactEmail: "lisa.park@freightpulse.io",
    tier: "Standard",
    accountManager: "Lisa Park",
    activeShipments: 29,
    exceptions: 0,
    slaTarget: 90,
    region: "South",
  },
  {
    id: "CUS-009",
    name: "Harbor Textiles",
    contactName: "Marcus Webb",
    contactEmail: "marcus.webb@freightpulse.io",
    tier: "Growth",
    accountManager: "Marcus Webb",
    activeShipments: 33,
    exceptions: 3,
    slaTarget: 92,
    region: "Midwest",
  },
  {
    id: "CUS-010",
    name: "Lakeside Pharma",
    contactName: "Sarah Chen",
    contactEmail: "sarah.chen@freightpulse.io",
    tier: "Enterprise",
    accountManager: "Sarah Chen",
    activeShipments: 41,
    exceptions: 1,
    slaTarget: 97,
    region: "Southeast",
  },
];

export const carrierPerformance: CarrierPerformance[] = [
  {
    carrier: "XPO Logistics",
    onTimePct: 94.2,
    activeLoads: 312,
    exceptions: 14,
    avgDelayHours: 8.4,
    trend: "down",
  },
  {
    carrier: "FedEx Freight",
    onTimePct: 96.1,
    activeLoads: 248,
    exceptions: 9,
    avgDelayHours: 6.2,
    trend: "up",
  },
  {
    carrier: "Schneider National",
    onTimePct: 91.8,
    activeLoads: 186,
    exceptions: 11,
    avgDelayHours: 11.3,
    trend: "down",
  },
  {
    carrier: "JB Hunt Intermodal",
    onTimePct: 88.5,
    activeLoads: 94,
    exceptions: 8,
    avgDelayHours: 18.7,
    trend: "down",
  },
  {
    carrier: "Werner Enterprises",
    onTimePct: 97.4,
    activeLoads: 156,
    exceptions: 3,
    avgDelayHours: 3.1,
    trend: "up",
  },
  {
    carrier: "Old Dominion Freight",
    onTimePct: 98.2,
    activeLoads: 201,
    exceptions: 2,
    avgDelayHours: 2.4,
    trend: "flat",
  },
];

export const delayReasonSummary: DelayReasonSummary[] = [
  { reason: "Weather / road closure", count: 28, pct: 24 },
  { reason: "Port & terminal congestion", count: 22, pct: 19 },
  { reason: "Missed linehaul connection", count: 18, pct: 15 },
  { reason: "Driver HOS / capacity", count: 16, pct: 14 },
  { reason: "Address verification", count: 12, pct: 10 },
  { reason: "Equipment / chassis shortage", count: 11, pct: 9 },
  { reason: "Other operational", count: 10, pct: 9 },
];

export const weeklyExceptionTrend: WeeklyTrendPoint[] = [
  { day: "Mon", exceptions: 18 },
  { day: "Tue", exceptions: 24 },
  { day: "Wed", exceptions: 31 },
  { day: "Thu", exceptions: 27 },
  { day: "Fri", exceptions: 37 },
  { day: "Sat", exceptions: 14 },
  { day: "Sun", exceptions: 9 },
];

export const operationalAlerts = [
  {
    id: "ALERT-901",
    title: "I-40 corridor weather advisory",
    detail:
      "NM & AZ segments affecting 23 active lanes. Average delay +18h. Carriers: Werner, Schneider, Swift.",
    severity: "Critical" as const,
    affected: 23,
    since: "May 27, 2026 · 11:42",
  },
  {
    id: "ALERT-898",
    title: "Long Beach terminal chassis shortage",
    detail:
      "LBCT gate delays 6–12h. Intermodal pickups suspended until May 29 06:00 PST.",
    severity: "High" as const,
    affected: 11,
    since: "May 27, 2026 · 08:15",
  },
  {
    id: "ALERT-895",
    title: "FedEx Freight Memphis hub backlog",
    detail:
      "Sort delay on outbound Midwest lanes. 7 shipments flagged for SLA review.",
    severity: "Medium" as const,
    affected: 7,
    since: "May 26, 2026 · 22:30",
  },
];

export const recentActivity = [
  {
    time: "5 min ago",
    actor: "System",
    event: "Auto-escalated FP-2026-084301 to Critical — SLA breach threshold exceeded",
    shipmentId: "FP-2026-084301",
    type: "escalation" as const,
  },
  {
    time: "18 min ago",
    actor: "Sarah Chen",
    event: "Contacted consignee for address verification on FP-2026-084088",
    shipmentId: "FP-2026-084088",
    type: "action" as const,
  },
  {
    time: "34 min ago",
    actor: "Carrier API",
    event: "FedEx Freight pushed revised ETA for FP-2026-084156 (+19h)",
    shipmentId: "FP-2026-084156",
    type: "update" as const,
  },
  {
    time: "1 hr ago",
    actor: "Marcus Webb",
    event: "Resolved exception on FP-2026-083902 — POD uploaded and matched",
    shipmentId: "FP-2026-083902",
    type: "resolved" as const,
  },
  {
    time: "1 hr ago",
    actor: "System",
    event: "Network alert ALERT-901 created — I-40 weather impact detected",
    shipmentId: null,
    type: "alert" as const,
  },
  {
    time: "2 hr ago",
    actor: "Carrier API",
    event: "JB Hunt reported chassis delay at Long Beach for FP-2026-084412",
    shipmentId: "FP-2026-084412",
    type: "update" as const,
  },
  {
    time: "3 hr ago",
    actor: "Lisa Park",
    event: "Opened investigation on FP-2026-084219 — missed Nashville connection",
    shipmentId: "FP-2026-084219",
    type: "action" as const,
  },
];

export const allCarriers = [
  ...new Set(shipmentRows.map((s) => s.carrier)),
].sort();

export const openExceptionsCount = initialExceptionRecords.filter(
  (e) => e.status !== "Resolved",
).length;
